#!/bin/bash

cd build/comm_render/
if $?; then
    rm -rf ./*
    cmake ../../enginee
    make
    cd ../..
fi 

cd build/comm_norender/
if $?; then
    rm -rf ./*
    cmake ../../enginee -DNO_RENDER:BOOL=ON
    make
    cd ../..
fi 

cd build/nocomm_render/
if $?; then
    rm -rf ./*
    cmake ../../enginee -DNOCOMM:BOOL=ON
    make
    cd ../..
fi

cd build/nocomm_norender/
if $?; then
    rm -rf ./*
    cmake ../../enginee -DNOCOMM:BOOL=ON -DNO_RENDER:BOOL=ON
    make
    cd ../..
fi

